# Generated by Django 4.1.3 on 2022-12-04 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='ready_datatime',
            field=models.DateTimeField(blank=True, verbose_name='Время готовности'),
        ),
    ]
