# Generated by Django 4.1.3 on 2022-12-04 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0004_alter_tasks_ready_datatime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='operator',
            field=models.CharField(blank=True, choices=[('YURA', 'Юрий'), ('ZIYO', 'Зийо'), ('AZIZ', 'Азиз'), ('DIMA', 'Дмитрий'), ('DEJURN', 'Дежурные')], max_length=255, verbose_name='Вывел'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='stage',
            field=models.BooleanField(choices=[('READY', 'Готов'), ('UNREADY', 'На машине')], default='На машине', verbose_name='Состояние'),
        ),
    ]
