# Generated by Django 4.1.3 on 2022-12-04 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0005_alter_tasks_operator_alter_tasks_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='stage',
            field=models.CharField(choices=[('READY', 'Готов'), ('UNREADY', 'На машине')], default='На машине', max_length=50, verbose_name='Состояние'),
        ),
    ]
